name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install runtime requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dev requirements
        run: pip install -r requirements-dev.txt

      - name: Lint & type check
        run: |
          test -f .flake8 || { echo "::error::Missing .flake8 configuration file"; exit 2; }
          flake8 --config .flake8 .
          flake8 --config .flake8 .
          black --check .
          isort --check-only .
          mypy .

      - name: Run tests with coverage
        run: pytest --cov=admin_gui --cov-report=term-missing
        - name: Upload coverage HTML artifact
          uses: actions/upload-artifact@v4
          with:
            name: coverage-html
            path: htmlcov
